import {IIssuesProcessorOptions} from '../../src/interfaces/issues-processor-options';

// Default options for use in tests.
// Mirrors the defaults defined in action.yml
export const DefaultProcessorOptions: IIssuesProcessorOptions = Object.freeze({
  repoToken: 'none',
  staleIssueMessage: 'This issue is stale',
  stalePrMessage: 'This PR is stale',
  rottenIssueMessage: 'This issue is rotten',
  rottenPrMessage: 'This PR is rotten',
  closeIssueMessage: 'This issue is being closed',
  closePrMessage: 'This PR is being closed',
  daysBeforeStale: 1,
  daysBeforeRotten: -1,
  daysBeforeIssueStale: NaN,
  daysBeforePrStale: NaN,
  daysBeforeIssueRotten: NaN,
  daysBeforePrRotten: NaN,
  daysBeforeClose: 30,
  daysBeforeIssueClose: NaN,
  daysBeforePrClose: NaN,
  staleIssueLabel: 'Stale',
  rottenIssueLabel: 'Rotten',
  closeIssueLabel: '',
  exemptIssueLabels: '',
  stalePrLabel: 'Stale',
  rottenPrLabel: 'Rotten',
  closePrLabel: '',
  exemptPrLabels: '',
  onlyLabels: '',
  onlyIssueLabels: '',
  onlyPrLabels: '',
  anyOfLabels: '',
  anyOfIssueLabels: '',
  anyOfPrLabels: '',
  operationsPerRun: 100,
  debugOnly: true,
  removeStaleWhenUpdated: false,
  removeIssueStaleWhenUpdated: undefined,
  removePrStaleWhenUpdated: undefined,
  removeRottenWhenUpdated: false,
  removeIssueRottenWhenUpdated: undefined,
  removePrRottenWhenUpdated: undefined,
  ascending: false,
  deleteBranch: false,
  startDate: '',
  exemptMilestones: '',
  exemptIssueMilestones: '',
  exemptPrMilestones: '',
  exemptAllMilestones: false,
  exemptAllIssueMilestones: undefined,
  exemptAllPrMilestones: undefined,
  exemptAssignees: '',
  exemptIssueAssignees: '',
  exemptPrAssignees: '',
  exemptAllAssignees: false,
  exemptAllIssueAssignees: undefined,
  exemptAllPrAssignees: undefined,
  enableStatistics: true,
  labelsToRemoveWhenStale: '',
  labelsToRemoveWhenUnstale: '',
  labelsToAddWhenUnstale: '',
  labelsToRemoveWhenRotten: '',
  labelsToRemoveWhenUnrotten: '',
  labelsToAddWhenUnrotten: '',
  ignoreUpdates: false,
  ignoreIssueUpdates: undefined,
  ignorePrUpdates: undefined,
  exemptDraftPr: false,
  closeIssueReason: 'not_planned',
  includeOnlyAssigned: false
});
