import {Issue} from '../src/classes/issue';
import {IIssuesProcessorOptions} from '../src/interfaces/issues-processor-options';
import {IssuesProcessorMock} from './classes/issues-processor-mock';
import {DefaultProcessorOptions} from './constants/default-processor-options';
import {generateIssue} from './functions/generate-issue';

interface ITestData {
  id: number;
  isPullRequest: boolean;
  assignees: string[];
  exemptAllIssueAssignees: boolean;
  exemptAllPrAssignees: boolean;
  exemptIssueAssignees: string;
  exemptPrAssignees: string;
  shouldStale: boolean;
  description: string;
}

describe('assignees options', (): void => {
  let opts: IIssuesProcessorOptions;
  let testIssueList: Issue[];
  let processor: IssuesProcessorMock;

  const setTestIssueList = (
    isPullRequest: boolean,
    assignees: string[],
    id: number
  ) => {
    testIssueList = [
      generateIssue(
        opts,
        id,
        'My first issue',
        '2020-01-01T17:00:00Z',
        '2020-01-01T17:00:00Z',
        isPullRequest,
        undefined,
        undefined,
        undefined,
        undefined,
        assignees
      )
    ];
  };

  const setProcessor = () => {
    processor = new IssuesProcessorMock(
      opts,
      async p => (p === 1 ? testIssueList : []),
      async () => [],
      async () => new Date().toDateString()
    );
  };

  beforeEach((): void => {
    opts = {...DefaultProcessorOptions};
  });

  describe.each`
    id      | isPullRequest | assignees       | exemptAllIssueAssignees | exemptAllPrAssignees | exemptIssueAssignees | exemptPrAssignees | shouldStale | description
    ${100}  | ${false}      | ${[]}           | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee'}
    ${101}  | ${false}      | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and only exemptAllAssignees is enabled'}
    ${102}  | ${false}      | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and only exemptAllIssueAssignees is enabled'}
    ${103}  | ${false}      | ${[]}           | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and only exemptAllPrAssignees is enabled'}
    ${104}  | ${false}      | ${[]}           | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is disabled'}
    ${105}  | ${false}      | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is enabled'}
    ${106}  | ${false}      | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is disabled'}
    ${107}  | ${false}      | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is enabled'}
    ${108}  | ${false}      | ${[]}           | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is disabled'}
    ${109}  | ${false}      | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue does not have an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is enabled'}
    ${200}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${201}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is enabled'}
    ${202}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and only exemptAllAssignees is enabled'}
    ${203}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and only exemptAllIssueAssignees is enabled'}
    ${204}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and only exemptAllPrAssignees is enabled'}
    ${205}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is disabled'}
    ${206}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is enabled'}
    ${207}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is disabled'}
    ${208}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is enabled'}
    ${209}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is disabled'}
    ${210}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is enabled'}
    ${211}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${212}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is enabled'}
    ${213}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${300}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${301}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${302}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${303}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${304}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${305}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${306}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${307}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${308}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${309}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${310}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${311}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${312}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${313}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${400}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${401}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${402}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${403}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${404}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${405}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${406}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${407}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${408}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${409}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${410}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${411}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${412}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${413}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${500}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${501}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${502}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${503}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${504}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${505}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${506}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${507}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${508}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${509}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${510}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${511}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${512}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${513}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${600}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${601}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${602}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${603}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${604}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${605}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${606}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${607}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${608}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${609}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${610}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${611}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${612}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${613}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${700}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${701}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${702}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${703}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${704}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${705}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${706}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${707}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${708}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${709}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${710}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${711}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${712}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${713}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${800}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${801}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${802}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${803}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${804}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${805}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${806}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${807}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${808}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${809}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${810}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${811}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${812}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${813}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${900}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${901}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${902}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${903}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${904}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${905}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${906}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${907}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${908}  | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${909}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${910}  | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${911}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${912}  | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${913}  | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${true}     | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1000} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1001} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1002} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${1003} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${1004} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${1005} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${1006} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${1007} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${1008} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${1009} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${1010} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${1011} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1012} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1013} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1100} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1101} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1102} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled'}
    ${1103} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled'}
    ${1104} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllPrAssignees is enabled'}
    ${1105} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${1106} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${1107} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${1108} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${1109} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${1110} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${1111} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1112} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1113} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1200} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1201} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1202} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1203} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1204} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1205} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1206} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1207} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1208} | ${false}      | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1209} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1210} | ${false}      | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1211} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1212} | ${false}      | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${1213} | ${false}      | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the issue has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${1300} | ${true}       | ${[]}           | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee'}
    ${1301} | ${true}       | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and only exemptAllAssignees is enabled'}
    ${1302} | ${true}       | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and only exemptAllIssueAssignees is enabled'}
    ${1303} | ${true}       | ${[]}           | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and only exemptAllPrAssignees is enabled'}
    ${1304} | ${true}       | ${[]}           | ${false}                | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is disabled'}
    ${1305} | ${true}       | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is enabled'}
    ${1306} | ${true}       | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is disabled'}
    ${1307} | ${true}       | ${[]}           | ${true}                 | ${true}              | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is enabled'}
    ${1308} | ${true}       | ${[]}           | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is disabled'}
    ${1309} | ${true}       | ${[]}           | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request does not have an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is enabled'}
    ${1400} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${1401} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is enabled'}
    ${1402} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and only exemptAllAssignees is enabled'}
    ${1403} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and only exemptAllIssueAssignees is enabled'}
    ${1404} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and only exemptAllPrAssignees is enabled'}
    ${1405} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is disabled'}
    ${1406} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptAllIssueAssignees is enabled'}
    ${1407} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is disabled'}
    ${1408} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptAllPrAssignees is enabled'}
    ${1409} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is disabled'}
    ${1410} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllIssueAssignees is enabled'}
    ${1411} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${1412} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${''}                | ${''}             | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is enabled'}
    ${1413} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${''}                | ${''}             | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled and exemptAllPrAssignees is disabled'}
    ${1500} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1501} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1502} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${1503} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${1504} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${1505} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${1506} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${1507} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${1508} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${1509} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${1510} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${1511} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1513} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1600} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1601} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1602} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${1603} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${1604} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${1605} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${1606} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${1607} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${1608} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${1609} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${1610} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${1611} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1612} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${1613} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${1701} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1702} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1703} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1704} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1705} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${1706} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1707} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${1708} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1709} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${1710} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has a different assignee'}
    ${1711} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has a different assignee'}
    ${1800} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1801} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1802} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1803} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${1804} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1805} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${1806} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1807} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${1808} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1809} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptIssueAssignees has the same assignee'}
    ${1810} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptIssueAssignees has the same assignee'}
    ${1900} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1901} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1902} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1903} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1904} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${1905} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1906} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${1907} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1908} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${1909} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1910} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has a different assignee'}
    ${1911} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has a different assignee'}
    ${2000} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${2001} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${2002} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${2003} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${2004} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${2005} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${2006} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${2007} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${2008} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${2009} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2010} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2100} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2101} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${2102} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${2103} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${2104} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${2105} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${2106} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${2107} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${2108} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${2109} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${2110} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'bad'}             | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2200} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2201} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2202} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${2203} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${2204} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${2205} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${2206} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${2207} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${2208} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${2209} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${2210} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${2311} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2312} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2313} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2300} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled'}
    ${2301} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2302} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled'}
    ${2303} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled'}
    ${2304} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled'}
    ${2305} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled'}
    ${2306} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled'}
    ${2307} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled'}
    ${2308} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled'}
    ${2309} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled'}
    ${2310} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'bad'}          | ${true}     | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled'}
    ${2311} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'bad'}          | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled'}
    ${2400} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${2401} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2402} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2403} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2404} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2405} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${2406} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2407} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${2408} | ${true}       | ${['assignee']} | ${true}                 | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is enabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2409} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${2410} | ${true}       | ${['assignee']} | ${true}                 | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllIssueAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2411} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
    ${2412} | ${true}       | ${['assignee']} | ${false}                | ${true}              | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is enabled and exemptPrAssignees has the same assignee'}
    ${2413} | ${true}       | ${['assignee']} | ${false}                | ${false}             | ${'assignee'}        | ${'assignee'}     | ${false}    | ${'when the pull request has an assignee and exemptAllAssignees is disabled, exemptAllPrAssignees is disabled and exemptPrAssignees has the same assignee'}
  `(
    '$description',
    ({
      id,
      isPullRequest,
      assignees,
      exemptAllIssueAssignees,
      exemptAllPrAssignees,
      exemptIssueAssignees,
      exemptPrAssignees,
      shouldStale
    }: ITestData): void => {
      beforeEach((): void => {
        opts.exemptAllIssueAssignees = exemptAllIssueAssignees;
        opts.exemptAllPrAssignees = exemptAllPrAssignees;
        opts.exemptIssueAssignees = exemptIssueAssignees;
        opts.exemptPrAssignees = exemptPrAssignees;
        setTestIssueList(isPullRequest, assignees, id);
        setProcessor();
      });

      test(`should${
        shouldStale ? '' : ' not'
      } be marked as stale`, async () => {
        expect.assertions(3);

        await processor.processIssues(1);

        expect(processor.staleIssues).toHaveLength(shouldStale ? 1 : 0);
        expect(processor.closedIssues).toHaveLength(0);
        expect(processor.removedLabelIssues).toHaveLength(0);
      });
    }
  );
});
