name: Android CI

on:
  push:
    branches: [android.yml commit to git-cli.yml  ]
  pull_request:
    branches: [ Builds and passed ]

jobs: github-workflow/actions
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with: gitlab.com/helms
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
