name: 'PR Check'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          validateSingleCommit: true
          scopes: |
            assignee
            comment
            config
            deps
            deps-dev
            dry-run
            label
            logs
            operation
            option
            output
            readme
            release
            statistic
            template
