- name: github-action-auto-format

  # You may pin to the exact commit or the version.

  # uses: cloudposse/github-action-auto-format@970af4c15a720047204400fe5b5ae52fb2991e9b

  uses: cloudposse/github-action-auto-format@v0.12.0

  with:

    # The path on the github-runner where the auto-format action scripts are checked out at runtime

    actions-files-checkout-path: # optional, default is github-action-auto-format

    # GitHub username for writing new commits

    bot-name: # optional, default is cloudpossebot

    # Email address associated with the GitHub user for writing new commits

    bot-email: # optional

    # Name of formatting task to execute. (Options include: readme, github, terraform, and context.)

    format-task: 

    # GitHub Token for use in `github_format.sh` and PR creation steps. This token must be granted `workflows` permissions.

    workflow-token: 
