name: Validate action typings

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

jobs:
  validate-typings:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Validate typings
        uses: krzema12/github-actions-typing@v0
